### PR TITLE
Add link to Seattle-specific climate jobs board

### PR DESCRIPTION
**Pull request by stevenqzhang**
Screen Shot 2023-10-04 at 12 15 15 AM
Screen Shot 2023-10-04 at 12 15 04 AM

### CODE REVIEW

**Comment by stevenqzhang** [comment]
@lowellbander is there anything else I need to do here besides have this PR up?

**Comment by lowellbander** [comment]
will u pls attach screenshots of how this renders on desktop and mobile? then i'll stamp!

**Comment by stevenqzhang** [comment]
@lowellbander attached screenshots!

**Review by lowellbander — DISMISSED** [review]
thank u contributor steven! <3 before merging, will you give the Jobs link the same treatment as the Newsletter link? (same line as that one, so that the external links are on one line and the anchors on the next)

**Comment by stevenqzhang** [comment]
Can you clarify what you mean? I *think* you meant making the classNames the same? LMK if that's correct/ the fix is right

**Comment by lowellbander** [comment]
> Can you clarify what you mean? I _think_ you meant making the classNames the same? LMK if that's correct/ the fix is right

apologies! i mean i figure it should look like

desktop:
```
[ Newsletter -> ][ Jobs -> ][ Meetup v ][ Slack v]
```

mobile:
```
[ Newsletter -> ][ Jobs -> ]
[ Meetup v ][ Slack v]
```

so that the external links are adjacent to each other (and same line on mobile), likewise for the anchor links

wyt?

sorry for the slow handling on this one!

**Comment by stevenqzhang** [comment]
Cool how about this?

image
image

**Review by lowellbander — APPROVED** [review]
Beautiful 😍

**Pull request merged**
